"""
ARAM Oracle — Diagnostics & Bug Report Collector

Ring-buffer based error/log/WS message collector.
Hooks into the ``aram-oracle`` logger hierarchy automatically.
Call ``collector.generate_report()`` to produce a JSON bug report file.
"""

import json
import logging
import platform
import sys
import traceback
from collections import deque
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger("aram-oracle.diagnostics")

REPORT_DIR = Path.home() / ".aram-oracle" / "bug-reports"

MAX_ERRORS = 50
MAX_LOG_ENTRIES = 200
MAX_WS_MESSAGES = 100


@dataclass
class ErrorEntry:
    timestamp: str
    level: str
    logger_name: str
    message: str
    traceback: str | None = None


@dataclass
class WsMessageEntry:
    timestamp: str
    direction: str  # "inbound" or "outbound"
    summary: str    # truncated


class DiagnosticsCollector:
    """Singleton that collects errors, logs, and WS messages for bug reports."""

    def __init__(self) -> None:
        self.errors: deque[ErrorEntry] = deque(maxlen=MAX_ERRORS)
        self.log_entries: deque[ErrorEntry] = deque(maxlen=MAX_LOG_ENTRIES)
        self.ws_messages: deque[WsMessageEntry] = deque(maxlen=MAX_WS_MESSAGES)
        self._handler: _DiagnosticsHandler | None = None

    def install_log_handler(self) -> None:
        """Attach a logging handler to the root 'aram-oracle' logger."""
        root = logging.getLogger("aram-oracle")
        self._handler = _DiagnosticsHandler(self)
        self._handler.setLevel(logging.DEBUG)
        root.addHandler(self._handler)

    def record_error(self, message: str, exc: BaseException | None = None) -> None:
        """Programmatic error capture with full traceback."""
        tb = None
        if exc is not None:
            tb = "".join(traceback.format_exception(type(exc), exc, exc.__traceback__))
        else:
            tb = "".join(traceback.format_stack())

        entry = ErrorEntry(
            timestamp=datetime.now(timezone.utc).isoformat(),
            level="ERROR",
            logger_name="programmatic",
            message=message,
            traceback=tb,
        )
        self.errors.append(entry)

    def record_ws_message(self, direction: str, raw: str) -> None:
        """Track a recent WebSocket message (truncated to 200 chars)."""
        self.ws_messages.append(WsMessageEntry(
            timestamp=datetime.now(timezone.utc).isoformat(),
            direction=direction,
            summary=raw[:200],
        ))

    def format_github_issue(
        self,
        game_state_dict: dict | None = None,
        user_description: str = "",
    ) -> tuple[str, str]:
        """Format a bug report as (title, markdown_body) for a GitHub issue."""
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        champ = game_state_dict.get("champion_id", "unknown") if game_state_dict else "unknown"

        title = f"[Bug Report] {champ} — {ts}"

        sections: list[str] = []

        if user_description.strip():
            sections.append(f"## Description\n\n{user_description.strip()}")

        sys_info = (
            f"- **Python:** {sys.version.split()[0]}\n"
            f"- **Platform:** {platform.platform()}\n"
            f"- **Screen:** {_get_screen_resolution()}\n"
            f"- **OCR:** {'Yes' if _check_ocr() else 'No'}"
        )
        sections.append(f"## System\n\n{sys_info}")

        if game_state_dict:
            gs_lines = [f"- **{key}:** `{val}`" for key, val in game_state_dict.items()]
            sections.append("## Game State\n\n" + "\n".join(gs_lines))

        recent_errors = list(self.errors)[-5:]
        if recent_errors:
            err_lines: list[str] = []
            for e in recent_errors:
                err_lines.append(f"### {e.timestamp}\n`{e.message}`")
                if e.traceback:
                    err_lines.append(
                        f"<details><summary>Traceback</summary>\n\n```\n{e.traceback}\n```\n</details>"
                    )
            sections.append("## Recent Errors\n\n" + "\n\n".join(err_lines))

        recent_logs = list(self.log_entries)[-20:]
        if recent_logs:
            log_text = "\n".join(
                f"[{e.timestamp}] {e.level} {e.logger_name}: {e.message}"
                for e in recent_logs
            )
            sections.append(
                f"## Recent Logs\n\n"
                f"<details><summary>Last {len(recent_logs)} log entries</summary>\n\n"
                f"```\n{log_text}\n```\n</details>"
            )

        body = "\n\n---\n\n".join(sections)
        body += "\n\n---\n*Generated by ARAM Oracle v0.1.0*"

        return title, body

    def generate_report(self, game_state_dict: dict | None = None) -> Path:
        """Build a JSON bug report file and return its path."""
        REPORT_DIR.mkdir(parents=True, exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        path = REPORT_DIR / f"bug_report_{ts}.json"

        report = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "system": {
                "python_version": sys.version,
                "platform": platform.platform(),
                "screen_resolution": _get_screen_resolution(),
                "ocr_available": _check_ocr(),
            },
            "recent_errors": [asdict(e) for e in self.errors],
            "recent_logs": [asdict(e) for e in self.log_entries],
            "recent_ws_messages": [asdict(m) for m in self.ws_messages],
            "game_state": game_state_dict,
        }

        path.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
        logger.info("Bug report saved: %s", path)
        return path


class _DiagnosticsHandler(logging.Handler):
    """Logging handler that feeds into DiagnosticsCollector."""

    def __init__(self, collector_instance: DiagnosticsCollector) -> None:
        super().__init__()
        self._collector = collector_instance

    def emit(self, record: logging.LogRecord) -> None:
        tb = None
        if record.exc_info and record.exc_info[1]:
            tb = "".join(traceback.format_exception(*record.exc_info))

        entry = ErrorEntry(
            timestamp=datetime.fromtimestamp(record.created, tz=timezone.utc).isoformat(),
            level=record.levelname,
            logger_name=record.name,
            message=record.getMessage(),
            traceback=tb,
        )
        self._collector.log_entries.append(entry)
        if record.levelno >= logging.ERROR:
            self._collector.errors.append(entry)


# Module-level singleton
collector = DiagnosticsCollector()


def _get_screen_resolution() -> str:
    if sys.platform != "win32":
        return "unknown (non-Windows)"
    try:
        import ctypes
        user32 = ctypes.windll.user32
        return f"{user32.GetSystemMetrics(0)}x{user32.GetSystemMetrics(1)}"
    except Exception:
        return "unknown"


def _check_ocr() -> bool:
    try:
        from backend.collectors.screen_ocr import is_available
        return is_available()
    except Exception:
        return False
