import json
import logging
from pathlib import Path

import backend.diagnostics as diag
from backend.diagnostics import DiagnosticsCollector


def test_error_ring_buffer_max_size():
    c = DiagnosticsCollector()
    for i in range(100):
        c.record_error(f"error {i}")
    assert len(c.errors) == diag.MAX_ERRORS


def test_log_ring_buffer_max_size():
    c = DiagnosticsCollector()
    for i in range(300):
        c.log_entries.append(
            diag.ErrorEntry(
                timestamp="t", level="INFO", logger_name="test", message=f"log {i}"
            )
        )
    assert len(c.log_entries) == diag.MAX_LOG_ENTRIES


def test_ws_message_tracking():
    c = DiagnosticsCollector()
    c.record_ws_message("inbound", '{"type": "snapshot"}')
    c.record_ws_message("outbound", '{"type": "update"}')
    assert len(c.ws_messages) == 2
    assert c.ws_messages[0].direction == "inbound"
    assert c.ws_messages[1].direction == "outbound"


def test_ws_message_truncated():
    c = DiagnosticsCollector()
    long_msg = "x" * 500
    c.record_ws_message("inbound", long_msg)
    assert len(c.ws_messages[0].summary) == 200


def test_record_error_with_exception():
    c = DiagnosticsCollector()
    try:
        raise ValueError("test error")
    except ValueError as e:
        c.record_error("caught", exc=e)
    assert len(c.errors) == 1
    assert "ValueError" in c.errors[0].traceback
    assert "test error" in c.errors[0].traceback


def test_record_error_without_exception():
    c = DiagnosticsCollector()
    c.record_error("manual error")
    assert len(c.errors) == 1
    assert c.errors[0].traceback is not None


def test_generate_report_creates_file(tmp_path, monkeypatch):
    monkeypatch.setattr(diag, "REPORT_DIR", tmp_path)
    c = DiagnosticsCollector()
    c.record_error("test error")
    c.record_ws_message("inbound", '{"type":"test"}')

    path = c.generate_report(game_state_dict={"level": 5})
    assert path.exists()
    assert path.suffix == ".json"

    data = json.loads(path.read_text(encoding="utf-8"))
    assert "system" in data
    assert "recent_errors" in data
    assert "recent_logs" in data
    assert "recent_ws_messages" in data
    assert data["game_state"]["level"] == 5
    assert len(data["recent_errors"]) == 1
    assert len(data["recent_ws_messages"]) == 1


def test_generate_report_without_game_state(tmp_path, monkeypatch):
    monkeypatch.setattr(diag, "REPORT_DIR", tmp_path)
    c = DiagnosticsCollector()
    path = c.generate_report()
    data = json.loads(path.read_text(encoding="utf-8"))
    assert data["game_state"] is None


def test_install_log_handler_captures_errors():
    c = DiagnosticsCollector()
    c.install_log_handler()
    test_logger = logging.getLogger("aram-oracle.test_diag")
    test_logger.error("something broke")
    assert any("something broke" in e.message for e in c.errors)
    assert any("something broke" in e.message for e in c.log_entries)


def test_install_log_handler_captures_info():
    c = DiagnosticsCollector()
    c.install_log_handler()
    test_logger = logging.getLogger("aram-oracle.test_diag_info")
    test_logger.setLevel(logging.DEBUG)
    test_logger.info("info message")
    assert any("info message" in e.message for e in c.log_entries)
    # INFO should not be in errors
    assert not any("info message" in e.message for e in c.errors)


# -- format_github_issue tests --


def test_format_github_issue_basic():
    c = DiagnosticsCollector()
    title, body = c.format_github_issue(
        game_state_dict={"champion_id": "jinx", "level": 11},
        user_description="Augment scoring was wrong",
    )
    assert "[Bug Report]" in title
    assert "jinx" in title
    assert "## Description" in body
    assert "Augment scoring was wrong" in body
    assert "## System" in body
    assert "## Game State" in body


def test_format_github_issue_no_description():
    c = DiagnosticsCollector()
    title, body = c.format_github_issue(
        game_state_dict={"champion_id": "lux"},
    )
    assert "## Description" not in body
    assert "## System" in body


def test_format_github_issue_errors_collapsed():
    c = DiagnosticsCollector()
    c.record_error("something broke")
    _, body = c.format_github_issue()
    assert "## Recent Errors" in body
    assert "<details>" in body
    assert "something broke" in body


def test_format_github_issue_empty_state():
    c = DiagnosticsCollector()
    title, body = c.format_github_issue()
    assert "unknown" in title
    assert "## System" in body
    assert "Generated by ARAM Oracle" in body
